// Interface text for the export tools, merged into src/i18n.js. Buyer-facing
// output (quotation sheet, emails) is English by design and lives with the
// code that writes it.

const EN = {
  nav_quoting: 'Quoting',
  nav_tracker: 'Samples',
  home_quoting_cta: 'Open the Quote Desk',
  home_tracker_cta: 'Open the Tracker',

  tl_cancel: 'Cancel',
  tl_days: '{n} days',
  tl_days_short: '{n}d',
  tl_hours: '{n} h',
  tl_in: 'in {span}',
  tl_late: '{span} late',
  tl_delete: 'Delete',
  tl_delete_confirm: 'Yes, delete',
  tl_saved_device: 'Saved on this device',
  tl_saved_guest: 'Saved in this browser only.',
  tl_synced: 'Synced to your account',
  tl_syncing: 'Syncing…',
  tl_sync_error: 'Sync failed. Your work is saved on this device.',

  q_kicker: 'Export quoting engine',
  q_title: 'Quote desk',
  q_valid_to: 'valid to {date}',
  q_expired: 'expired',
  q_no_buyer: 'No buyer yet',
  q_quotes: 'Saved quotes ({n})',
  q_new: 'New quote',
  q_revise: 'New revision',
  q_revised: 'Revision created',
  q_print: 'Print quotation',
  q_example_note: 'Example figures. Replace them with your own costs and your forwarder’s rates before sending anything.',
  q_start: 'Start with your first product on the left, or load a worked example to see every panel filled in.',
  q_load_example: 'Load an example',
  q_to_tracker: 'Log a sample request for this buyer',
  q_to_tracker_hint: 'Opens the Sample & After-Sales Tracker with this buyer and these products filled in.',
  q_inputs: 'Quote inputs',
  q_s_parties: 'Buyer',
  q_s_lines: 'Products',
  q_s_route: 'Route & freight',
  q_s_money: 'Money & terms',
  q_s_margin: 'Margin & tax',
  q_buyer: 'Buyer company',
  q_buyer_ph: 'As it should appear on the quotation',
  q_contact: 'Contact person',
  q_city: 'City',
  q_you: 'Your details on the quotation',
  q_you_company: 'Your company',
  q_you_address: 'Address',
  q_you_name: 'Your name',
  q_you_email: 'Email',
  q_you_phone: 'Phone',
  q_you_hint: 'Saved on this device and used on every quotation and email.',
  q_lines_n: '{n} lines',
  q_line_name: 'Product',
  q_line_name_ph: 'Product name, e.g. Brass ball valve DN25',
  q_unit_cost: 'Unit cost',
  q_qty: 'Quantity',
  q_price_override: 'Your price',
  q_price_auto: 'Calculated: {p}. Type a price to override it.',
  q_auto: 'Auto',
  q_cost_incl_vat: 'Unit cost includes VAT (含税价)',
  q_line_more: 'Packing, HS code and tax rates',
  q_line_less: 'Hide details',
  q_spec: 'Specification',
  q_spec_ph: 'Material, rating, finish',
  q_hs: 'HS code',
  q_packing: 'Export carton',
  q_per_carton: 'Pcs / carton',
  q_carton_kg: 'Gross weight / carton',
  q_upright: 'This side up',
  q_rebate: 'Export VAT rebate',
  q_rebate_hint: 'The rate for this HS code, 0–13%. Rates change: check before quoting.',
  q_duty: 'Import duty at destination',
  q_duty_hint: 'Used for DDP only. Include extra tariffs such as US Section 301.',
  q_line_dup: 'Duplicate',
  q_line_remove: 'Remove',
  q_line_add: '+ Add product',
  q_paste: 'Paste from Excel',
  q_paste_hint: 'One product per row: name, quantity, unit cost ¥, pcs/carton, carton L, W, H (cm), kg/carton, HS code.',
  q_paste_add: 'Add rows',
  q_paste_none: 'No rows with a product name were found.',
  q_paste_done: 'Added {n} products',
  q_origin: 'Port of loading',
  q_origin_place: 'Factory location',
  q_origin_place_ph: 'City, province (for EXW)',
  q_dest_country: 'Destination country',
  q_dest_other: 'Another country',
  q_dest_port: 'Port of discharge',
  q_dest_place: 'Buyer’s delivery address',
  q_dest_place_ph: 'City (for DAP and DDP)',
  q_rates: 'Your forwarder’s rates',
  q_rate_freight: 'Sea / air freight ($)',
  q_rate_origin: 'Origin charges (¥)',
  q_rate_haulage: 'Haulage to port (¥)',
  q_rate_dest: 'Destination charges ($)',
  q_rate_delivery: 'Delivery to door ($)',
  q_rate_unit: 'Charged per',
  q_per_wm: 'W/M',
  q_per_box: 'box',
  q_per_kg: 'kg',
  q_air: 'Air',
  q_rates_hint: 'Leave a column empty if that option is not offered. Haulage and delivery are per box for FCL and per shipment for LCL and air. Nexallure never guesses freight.',
  q_export_docs: 'Export customs & docs',
  q_import_broker: 'Import customs broker',
  q_payload: 'Weight limit per box',
  q_currency: 'Quote currency',
  q_fx: '¥ per {cur}',
  q_fx_fetch: 'Get reference rates',
  q_fx_loading: 'Fetching…',
  q_fx_done: 'Reference rates of {date} loaded',
  q_fx_failed: 'Couldn’t reach the rate service. Enter your bank’s rate.',
  q_fx_hint: 'Use the rate your bank will actually give you.',
  q_fx_asof: 'ECB reference rate of {date}. Your bank’s buying rate will be a little lower.',
  q_payment: 'Payment terms',
  q_pay_TT_ADVANCE: 'T/T 100% in advance',
  q_pay_TT_30_70_BL: 'T/T 30% deposit, 70% against B/L copy',
  q_pay_TT_30_70_BEFORE: 'T/T 30% deposit, 70% before shipment',
  q_pay_LC_SIGHT: 'L/C at sight',
  q_pay_LC_60: 'L/C 60 days',
  q_pay_DP_SIGHT: 'D/P at sight',
  q_pay_OA_30: 'Open account, 30 days',
  q_pay_OA_60: 'Open account, 60 days',
  q_tranche: '{pct}% paid, days after shipping',
  q_tranche_hint: 'Negative means before the goods ship.',
  q_days_short: 'days',
  q_capital: 'Cost of money',
  q_bank_pct: 'Bank charges',
  q_bank_flat: 'Bank fixed fees',
  q_sinosure: 'Sinosure premium',
  q_commission: 'Agent commission',
  q_insurance: 'Cargo insurance rate',
  q_insurance_hint: 'On {m}% of the CIF value, as Incoterms® require.',
  q_entity: 'Who exports',
  q_entity_mfr: 'Manufacturer · 免抵退',
  q_entity_trader: 'Trading company · 免退',
  q_entity_mfr_hint: 'The gap between the VAT rate and the rebate rate is charged on the FOB value.',
  q_entity_trader_hint: 'The rebate is paid on your purchase cost; the gap to the VAT rate is a cost.',
  q_margin: 'Target margin',
  q_margin_basis: 'Margin on',
  q_basis_price: 'Selling price',
  q_basis_cost: 'Cost (markup)',
  q_overhead: 'Overhead',
  q_overhead_hint: 'Added to the cost before VAT.',
  q_floor: 'Lowest acceptable margin',
  q_vat: 'China VAT rate',
  q_decimals: 'Round unit prices to',
  q_valid: 'Quote valid for',
  q_lead: 'Lead time',
  q_dest_tax: 'Destination taxes, for DDP',
  q_valuation: 'Duty charged on',
  q_valuation_cif: 'CIF value (EU, UK, most)',
  q_valuation_fob: 'FOB value (US, Canada, Australia)',
  q_import_vat: 'Import VAT / GST',
  q_import_fees: 'Other import fees',
  q_import_fees_us: 'MPF 0.3464% (with a minimum and a cap) + HMF 0.125%.',
  q_vat_recoverable: 'We can reclaim the import VAT',
  q_notes: 'Notes on the quotation',
  q_notes_hint: 'Printed on the quotation, which is in English. Leave empty for standard wording.',
  q_sheet_terms: 'Also show on the quotation',
  q_quoting_term: 'Quoting',
  q_term: 'Incoterm',
  q_total_at: 'Total {term}',
  q_shipment_sum: '{ctn} cartons · {cbm} m³ · {kg} kg',
  q_margin_earned: 'Margin earned',
  q_markup_earned: 'Markup earned',
  q_profit_is: '{v} profit on this order',
  q_fx_cost: '换汇成本 · FX cost',
  q_fx_cost_is: 'Yuan spent for each unit of foreign currency earned at FOB. Today’s rate: {rate} per {cur}.',
  q_w_part_carton: '{line}: the last carton holds only {n} pcs.',
  q_w_rebate_gt_vat: '{line}: the rebate rate is higher than the VAT rate.',
  q_w_no_carton: '{line}: the carton size is missing, so it cannot be loaded or share freight.',
  q_w_ddp_no_duty: '{line}: import duty is 0%. Check the tariff for this HS code before quoting DDP.',
  q_w_no_fx: 'An exchange rate is missing. Enter yuan per unit of the quote currency before trusting any price.',
  q_w_no_plan: 'No shipping option fits. Enter at least one freight rate and check the carton fits through a container door.',
  q_w_sea_term_air: '{term} is for sea freight only. For air, quote FCA, CPT or CIP.',
  q_w_fca_hint: 'Containers are handed over at the terminal, not on board. Incoterms® 2020 recommends FCA rather than FOB for container cargo.',
  q_w_below_floor: 'The margin is below your lowest acceptable margin.',
  q_w_lcl_big: 'Over 15 m³ in LCL. A full container is usually cheaper and safer.',
  q_ladder: 'Incoterm ladder',
  q_ladder_basis: 'Show',
  q_ladder_order: 'Whole order',
  q_ladder_unit: 'Per unit: {name}',
  q_ladder_hint: 'Each term is priced as its own quote, at the margin your quoted price earns. Click a term to quote it.',
  q_add_haulage: '+ haulage, customs',
  q_add_origin: '+ port charges',
  q_add_freight: '+ freight',
  q_add_insurance: '+ insurance',
  q_add_dest: '+ destination, delivery',
  q_add_duty: '+ duty, import VAT',
  q_breakdown: 'Where the price goes',
  q_breakdown_hint: 'One unit at {term}, {price}.',
  q_part_goods: 'Goods, before VAT',
  q_part_overhead: 'Overhead',
  q_part_tax: 'VAT not refunded',
  q_part_origin: 'Haulage, customs, port',
  q_part_freight: 'Freight and insurance',
  q_part_destination: 'Destination, duty, tax',
  q_part_terms: 'Commission, bank, credit',
  q_part_profit: 'Profit',
  q_load: 'Load plan',
  q_load_empty: 'Add products with carton sizes and at least one freight rate to see how they load.',
  q_load_air: 'Air freight is charged on the greater of actual weight and volume weight (1 m³ = 167 kg).',
  q_load_lcl: 'LCL is charged per W/M: cubic metres or tonnes, whichever is greater, minimum 1.',
  q_load_view: '{type} holding {n} cartons',
  q_volume: 'Volume',
  q_weight: 'Weight',
  q_length: 'Floor length',
  q_ctns: '{n} ctns',
  q_wall: 'wall',
  q_fill: 'more cartons of {name} still fit. Offer {qty} pcs to fill the box: freight per unit falls {drop}, and the order grows by {value}.',
  q_fill_apply: 'Use this quantity',
  q_modes: 'Every way to ship it',
  q_mode: 'Option',
  q_fill_col: 'Last box full',
  q_to_port_unit: 'Freight / unit',
  q_cheapest: 'Cheapest',
  q_plan_auto: 'Go back to the cheapest option',
  q_modes_hint: 'Cost per unit to the destination port, including haulage and origin charges. Click an option to use it.',
  q_mode_lcl: 'LCL {n} W/M',
  q_mode_air: 'Air {n} kg',
  q_money: 'Exchange rate and tax',
  q_breakeven: 'Break-even rate',
  q_breakeven_is: 'The yuan can strengthen {pct} against the {cur} before this quote loses money.',
  q_breakeven_none: 'This quote loses money at today’s rate.',
  q_rebate_mfr: 'Rebate ceiling · 免抵退税额',
  q_rebate_trader: 'Rebate refund · 退税额',
  q_rebate_is: 'VAT you cannot recover: {v}.',
  q_finance: 'Cost of waiting to be paid',
  q_sens: 'What if the rate or freight moves?',
  q_sens_label: 'Margin at the quoted prices',
  q_sens_corner: 'Freight ↓ ¥ →',
  q_sens_today: 'Today',
  q_sens_hint: 'Rows: change in freight. Columns: yuan per unit of the quote currency. Red is below your lowest margin; green meets your target.',
  q_sens_hint_fob: 'You quoted {term}, so freight is the buyer’s risk and every row is the same. Columns: yuan per unit of the quote currency.',
  q_breaks: 'Price by container load',
  q_breaks_load: 'Order',
  q_breaks_total: 'Total',
  q_breaks_now: 'This quote',
  q_breaks_full: 'A full {type}',
  q_breaks_hint: 'Every product scaled by the same factor until one box is full. Use it as a volume price list.',
  q_list_title: 'Saved quotes',
  q_list_label: '{n} quotes',
  q_list_drift_hint: 'Coloured margins show what open quotes earn at the reference rate of {date}.',
  q_list_empty: 'No saved quotes yet.',
  q_list_quote: 'Quote',
  q_list_status: 'Status',
  q_list_total: 'Total',
  q_list_margin: 'Margin',
  q_list_actions: 'Actions',
  q_list_today: 'now {m}',
  q_status_draft: 'Draft',
  q_status_sent: 'Sent',
  q_status_won: 'Won',
  q_status_lost: 'Lost',
  q_duplicate: 'Duplicate',
  q_duplicated: 'Copied as a new quote',

  tr_kicker: 'Sample & after-sales tracker · {n} open',
  tr_title: 'Every buyer thread, one board',
  tr_import: 'Import CSV',
  tr_export: 'Export CSV',
  tr_new_case: 'New after-sales case',
  tr_new_sample: '+ Log a sample',
  tr_kpi_win: 'Sample → order',
  tr_kpi_win_n: '{won} won of {n} decided',
  tr_kpi_days: 'Median days to PO',
  tr_kpi_days_n: 'from request to purchase order',
  tr_kpi_spend: 'Sample spend',
  tr_kpi_spend_n: 'goods and courier, last {n} days',
  tr_kpi_roi: 'Won per ¥1 sampled',
  tr_kpi_roi_n: 'orders worth {po}',
  tr_kpi_8d: 'Contained on time',
  tr_kpi_8d_n: 'Open cases: {n}',
  tr_today: 'Today',
  tr_today_n: '{n} to do',
  tr_today_empty: 'Nothing due in the next 24 hours.',
  tr_open: 'Open',
  tr_act_touch_short: 'Contacted',
  tr_touched: 'Logged',
  tr_track: 'Track',
  tr_snooze_1: 'Snooze 1 day',
  tr_snooze_2: 'Snooze 2 days',
  tr_snooze_7: 'Snooze a week',
  tr_why_approve: 'New request: approve it and confirm a date to the buyer.',
  tr_why_update: 'In production: send the buyer an update.',
  tr_why_qc: 'Check QC and send photos before dispatch.',
  tr_why_track: 'In transit {n} days: check the tracking.',
  tr_why_feedback: 'Landed {n} days ago: ask for feedback.',
  tr_why_cold: 'Landed {n} days ago and going cold.',
  tr_why_step: '{step} {name} is due.',
  tr_tab_samples: 'Samples · {n}',
  tr_tab_cases: 'After-sales · {n}',
  tr_tab_insights: 'Insights',
  tr_search: 'Search buyer, product, AWB…',
  tr_all_countries: 'All countries',
  tr_board_hint: 'The bar on each card is buyer warmth. It cools every day nobody replies, fastest once a parcel has landed. Drag a card to move it.',
  tr_empty_samples: 'No samples yet',
  tr_empty_samples_body: 'Log each sample request as it comes in. The tracker tells you when to chase each buyer.',
  tr_import_hint: 'Already tracking in Excel? Import a CSV with columns such as Buyer, Country, Product, Qty, Courier, AWB. Chinese headers work too.',
  tr_empty_cases: 'No after-sales cases',
  tr_empty_cases_body: 'When a buyer reports a problem, open a case. Each one follows the 8D method with the deadlines buyers expect.',
  tr_col_requested: 'Requested',
  tr_col_making: 'Making & QC',
  tr_col_transit: 'In transit',
  tr_col_delivered: 'Awaiting feedback',
  tr_col_decided: 'Decided',
  tr_ccol_open: 'Open',
  tr_ccol_contained: 'Contained',
  tr_ccol_fixing: 'Fixing',
  tr_ccol_preventing: 'Preventing',
  tr_ccol_closed: 'Closed',
  tr_stage: 'Stage',
  tr_stage_requested: 'Requested',
  tr_stage_making: 'Making',
  tr_stage_qc: 'QC',
  tr_stage_transit: 'In transit',
  tr_stage_delivered: 'Delivered',
  tr_stage_won: 'Won',
  tr_stage_lost: 'Lost',
  tr_no_buyer: 'Unnamed buyer',
  tr_card_won: 'PO ${v}',
  tr_card_lost: 'Lost · {r}',
  tr_policy_free: 'Free',
  tr_policy_buyer_pays: 'Buyer pays',
  tr_policy_credit: 'Credited on first order',
  tr_import_big: 'That file is over 2 MB. Split it and import it in parts.',
  tr_import_none: 'No rows found. The first row must name the columns.',
  tr_imported: 'Imported {n} samples',
  tr_deleted: 'Deleted',
  tr_sample_label: 'Sample',
  tr_case_label: 'After-sales case',
  tr_next_contact: 'Next contact',
  tr_warmth: 'Warmth',
  tr_next_action: 'Next step',
  tr_act_approve: 'Approve and start making',
  tr_act_qc: 'Made: move to QC',
  tr_act_dispatch: 'Dispatch',
  tr_act_delivered: 'Mark delivered',
  tr_act_won: 'Won: log the PO',
  tr_act_lost: 'Mark lost',
  tr_act_reopen: 'Reopen',
  tr_act_touch: 'Log contact',
  tr_courier: 'Courier',
  tr_courier_other: 'Other',
  tr_awb: 'Tracking number',
  tr_po_value: 'Purchase order value',
  tr_lost_reason: 'Why it was lost',
  tr_lost_price: 'Price',
  tr_lost_quality: 'Quality',
  tr_lost_lead_time: 'Lead time',
  tr_lost_no_reply: 'Buyer stopped replying',
  tr_lost_cancelled: 'Project cancelled',
  tr_lost_competitor: 'Chose a competitor',
  tr_lost_other: 'Other',
  tr_won_po: 'Won · PO ${v}',
  tr_lost_because: 'Lost · {r}',
  tr_contact_note: 'What was said',
  tr_contact_note_ph: 'e.g. Testing finishes next week',
  tr_details: 'Details',
  tr_buyer: 'Buyer',
  tr_country: 'Country',
  tr_contact: 'Contact',
  tr_email: 'Email',
  tr_item: 'Product',
  tr_qty: 'Quantity',
  tr_cost_policy: 'Who pays',
  tr_goods_cost: 'Sample cost',
  tr_courier_cost: 'Courier cost',
  tr_notes: 'Notes',
  tr_track_with: 'Track on {c}',
  tr_links: 'Linked',
  tr_open_quote: 'Open the quote',
  tr_make_quote: 'Make a quote',
  tr_open_case: 'Open an after-sales case',
  tr_from_sample: 'From sample {ref}',
  tr_activity: 'Activity',
  tr_log_created: 'Created',
  tr_log_stage: 'Moved to {stage}',
  tr_log_touch: 'Contacted',
  tr_log_snooze: 'Snoozed {n} days',
  tr_log_step: '{step} done',
  tr_delete_sample: 'Delete this sample',
  tr_delete_case: 'Delete this case',
  tr_compose: 'Write to the buyer',
  tr_compose_lang: 'In English',
  tr_compose_template: 'Message',
  tr_compose_tone: 'Tone',
  tr_tone_formal: 'Formal',
  tr_tone_friendly: 'Friendly',
  tr_subject: 'Subject',
  tr_copy: 'Copy',
  tr_copied: 'Copied',
  tr_copy_failed: 'Could not copy. Select the text and copy it yourself.',
  tr_open_email: 'Open in email',
  tr_compose_hint: 'Written from this record only, nothing is sent anywhere. Read it before sending; text in [brackets] needs yours.',
  tr_tpl_dispatched: 'Samples dispatched',
  tr_tpl_delivered: 'Samples arrived',
  tr_tpl_feedback: 'Ask for feedback',
  tr_tpl_cold: 'Rekindle a quiet buyer',
  tr_tpl_won: 'Thank you for the order',
  tr_tpl_acknowledge: 'Complaint received',
  tr_tpl_containment: 'Containment in place',
  tr_tpl_rootcause: 'Root cause and fix',
  tr_tpl_close: 'Case closed',
  tr_opened: 'Opened {date}',
  tr_8d: '8D progress',
  tr_8d_hint: 'Deadlines count from when the case was opened',
  tr_d_D0: 'Prepare',
  tr_d_D1: 'Team',
  tr_d_D2: 'Describe',
  tr_d_D3: 'Contain',
  tr_d_D4: 'Root cause',
  tr_d_D5: 'Choose fix',
  tr_d_D6: 'Validate',
  tr_d_D7: 'Prevent',
  tr_d_D8: 'Close',
  tr_d_D0_help: 'Collect the facts: photos, lot numbers, quantities. Decide whether an emergency response is needed.',
  tr_d_D1_help: 'Name the people who will solve it: quality, production, and whoever speaks to the buyer.',
  tr_d_D2_help: 'Describe the problem in numbers: what, where, when, how many (5W2H).',
  tr_d_D3_help: 'Protect the buyer now: sort or quarantine stock, replace goods, hold shipments. Buyers expect this within 24 hours.',
  tr_d_D4_help: 'Find why it happened and why it was not caught, and prove it with data.',
  tr_d_D5_help: 'Choose the permanent fix for each root cause.',
  tr_d_D6_help: 'Put the fix in place and show that it works.',
  tr_d_D7_help: 'Change procedures, drawings or checks so it cannot happen on other products.',
  tr_d_D8_help: 'Confirm with the buyer, thank the team, and close the case.',
  tr_step_done: 'Done',
  tr_done_at: 'Done {date}',
  tr_step_note: 'What was done',
  tr_step_reopen: 'Reopen this step',
  tr_step_complete: 'Mark {step} done',
  tr_sev_critical: 'Critical',
  tr_sev_major: 'Major',
  tr_sev_minor: 'Minor',
  tr_type_quality: 'Quality defect',
  tr_type_shortage: 'Short or wrong goods',
  tr_type_damage: 'Transit damage',
  tr_type_docs: 'Documents',
  tr_type_late: 'Late delivery',
  tr_type_other: 'Other',
  tr_case_title: 'Problem',
  tr_case_title_ph: 'e.g. Seat leak on DN65 valves',
  tr_severity: 'Severity',
  tr_type: 'Type',
  tr_product: 'Product',
  tr_po_ref: 'PO number',
  tr_lot: 'Lot / batch',
  tr_claim: 'Claim value',
  tr_affected: 'Affected quantity',
  tr_total_qty: 'Shipped quantity',
  tr_root_cause: 'Root cause',
  tr_resolution: 'Settlement',
  tr_case_cost: 'Cost to us',
  tr_case_cost_hint: 'Replacement goods, freight, credit notes, labour. Feeds the cost-of-quality chart.',
  tr_cause_material: 'Material',
  tr_cause_process: 'Process',
  tr_cause_design: 'Design',
  tr_cause_packaging: 'Packaging',
  tr_cause_transport: 'Transport',
  tr_cause_supplier: 'Supplier',
  tr_cause_human: 'Human error',
  tr_cause_unknown: 'Not found yet',
  tr_res_replacement: 'Replacement',
  tr_res_credit: 'Credit note',
  tr_res_refund: 'Refund',
  tr_res_repair: 'Repair',
  tr_res_rework: 'Rework',
  tr_res_rejected: 'Claim rejected',
  tr_insights_empty: 'Nothing to analyse yet',
  tr_insights_empty_body: 'Insights appear once you have logged samples or after-sales cases.',
  tr_period: 'Period',
  tr_period_days: 'Last {n} days',
  tr_fx_setting: '¥ per USD, for returns',
  tr_funnel: 'From request to order',
  tr_funnel_requested: 'Requested',
  tr_funnel_transit: 'Dispatched',
  tr_funnel_delivered: 'Delivered',
  tr_funnel_won: 'Won an order',
  tr_funnel_hint: '{rate} of decided samples became orders ({won} of {n}).',
  tr_funnel_none: 'No samples decided yet.',
  tr_dwell: 'Where samples wait',
  tr_dwell_hint: 'Median days in each stage. The longest, in rust, is where to look first.',
  tr_by_country: 'By country',
  tr_samples_n: 'Samples',
  tr_win: 'Win rate',
  tr_spend: 'Spend',
  tr_po_sum: 'Orders',
  tr_lost_why: 'Why samples are lost',
  tr_lost_none: 'No lost samples in this period.',
  tr_pareto: 'Cost of quality by root cause',
  tr_pareto_none: 'No after-sales costs logged in this period.',
  tr_pareto_hint: 'Rust bars make up the first 80% of the cost. Fixing those causes pays back first.',
  tr_quality_share: '{pct} of order value',
}

const ZH = {
  nav_quoting: '报价',
  nav_tracker: '样品售后',
  home_quoting_cta: '打开报价台',
  home_tracker_cta: '打开追踪器',

  tl_cancel: '取消',
  tl_days: '{n} 天',
  tl_days_short: '{n}天',
  tl_hours: '{n} 小时',
  tl_in: '{span}后',
  tl_late: '已逾期 {span}',
  tl_delete: '删除',
  tl_delete_confirm: '确认删除',
  tl_saved_device: '已保存在本设备',
  tl_saved_guest: '仅保存在此浏览器。',
  tl_synced: '已同步到你的账户',
  tl_syncing: '同步中…',
  tl_sync_error: '同步失败，内容已保存在本设备。',

  q_kicker: '出口报价引擎',
  q_title: '报价台',
  q_valid_to: '有效期至 {date}',
  q_expired: '已过期',
  q_no_buyer: '尚未填写买家',
  q_quotes: '已存报价（{n}）',
  q_new: '新建报价',
  q_revise: '新版本',
  q_revised: '已创建新版本',
  q_print: '打印报价单',
  q_example_note: '以下为示例数据。发出任何报价前，请换成你自己的成本和货代运价。',
  q_start: '从左侧填写第一个产品，或载入一个完整示例，看看每个面板的效果。',
  q_load_example: '载入示例',
  q_to_tracker: '为该买家登记样品申请',
  q_to_tracker_hint: '打开样品与售后追踪器，并自动填好买家和产品。',
  q_inputs: '报价输入',
  q_s_parties: '买家',
  q_s_lines: '产品',
  q_s_route: '路线与运费',
  q_s_money: '汇率与付款',
  q_s_margin: '利润与税',
  q_buyer: '买家公司',
  q_buyer_ph: '报价单上显示的公司名称',
  q_contact: '联系人',
  q_city: '城市',
  q_you: '报价单上的我方信息',
  q_you_company: '我方公司',
  q_you_address: '地址',
  q_you_name: '你的姓名',
  q_you_email: '邮箱',
  q_you_phone: '电话',
  q_you_hint: '保存在本设备，用于每份报价单和邮件。',
  q_lines_n: '{n} 个产品',
  q_line_name: '产品',
  q_line_name_ph: '产品名称，例如 黄铜球阀 DN25',
  q_unit_cost: '单位成本',
  q_qty: '数量',
  q_price_override: '你的报价',
  q_price_auto: '计算结果：{p}。输入价格可覆盖。',
  q_auto: '自动',
  q_cost_incl_vat: '单位成本为含税价',
  q_line_more: '包装、HS 编码和税率',
  q_line_less: '收起',
  q_spec: '规格',
  q_spec_ph: '材质、压力等级、表面处理',
  q_hs: 'HS 编码',
  q_packing: '出口纸箱',
  q_per_carton: '每箱件数',
  q_carton_kg: '每箱毛重',
  q_upright: '此面朝上',
  q_rebate: '出口退税率',
  q_rebate_hint: '该 HS 编码的退税率（0–13%）。税率会调整，报价前请核实。',
  q_duty: '目的国进口关税',
  q_duty_hint: '仅用于 DDP。请把额外关税（如美国 301 关税）一并计入。',
  q_line_dup: '复制',
  q_line_remove: '删除',
  q_line_add: '+ 添加产品',
  q_paste: '从 Excel 粘贴',
  q_paste_hint: '每行一个产品：品名、数量、单位成本 ¥、每箱件数、箱长、宽、高（厘米）、每箱毛重、HS 编码。',
  q_paste_add: '添加这些行',
  q_paste_none: '没有找到带品名的行。',
  q_paste_done: '已添加 {n} 个产品',
  q_origin: '起运港',
  q_origin_place: '工厂所在地',
  q_origin_place_ph: '城市、省份（用于 EXW）',
  q_dest_country: '目的国',
  q_dest_other: '其他国家',
  q_dest_port: '目的港',
  q_dest_place: '买家收货地',
  q_dest_place_ph: '城市（用于 DAP 和 DDP）',
  q_rates: '你的货代运价',
  q_rate_freight: '海运 / 空运费（$）',
  q_rate_origin: '起运港杂费（¥）',
  q_rate_haulage: '拖车到港（¥）',
  q_rate_dest: '目的港杂费（$）',
  q_rate_delivery: '派送到门（$）',
  q_rate_unit: '计费单位',
  q_per_wm: '计费吨',
  q_per_box: '柜',
  q_per_kg: '公斤',
  q_air: '空运',
  q_rates_hint: '没有的运输方式留空即可。整柜的拖车和派送按柜计，拼箱和空运按票计。Nexallure 从不猜测运费。',
  q_export_docs: '出口报关和单证费',
  q_import_broker: '目的国清关代理费',
  q_payload: '每柜限重',
  q_currency: '报价币种',
  q_fx: '每 {cur} 兑人民币',
  q_fx_fetch: '获取参考汇率',
  q_fx_loading: '获取中…',
  q_fx_done: '已载入 {date} 的参考汇率',
  q_fx_failed: '无法连接汇率服务，请填入银行汇率。',
  q_fx_hint: '请用银行实际给你的结汇汇率。',
  q_fx_asof: '欧洲央行 {date} 参考汇率。银行结汇价通常略低。',
  q_payment: '付款方式',
  q_pay_TT_ADVANCE: 'T/T 100% 预付',
  q_pay_TT_30_70_BL: 'T/T 30% 定金，70% 见提单副本付款',
  q_pay_TT_30_70_BEFORE: 'T/T 30% 定金，70% 出货前付清',
  q_pay_LC_SIGHT: '即期信用证',
  q_pay_LC_60: '60 天远期信用证',
  q_pay_DP_SIGHT: '即期付款交单 D/P',
  q_pay_OA_30: '赊销 30 天',
  q_pay_OA_60: '赊销 60 天',
  q_tranche: '{pct}% 货款：出货后第几天到账',
  q_tranche_hint: '负数表示出货前到账。',
  q_days_short: '天',
  q_capital: '资金成本',
  q_bank_pct: '银行手续费',
  q_bank_flat: '银行固定费用',
  q_sinosure: '中国信保费率',
  q_commission: '中间商佣金',
  q_insurance: '货运保险费率',
  q_insurance_hint: '按 CIF 价的 {m}% 投保，符合国际贸易术语的要求。',
  q_entity: '出口主体',
  q_entity_mfr: '生产企业 · 免抵退',
  q_entity_trader: '外贸企业 · 免退',
  q_entity_mfr_hint: '征税率与退税率之差按 FOB 价计入成本（不得免征和抵扣税额）。',
  q_entity_trader_hint: '按含税采购成本退税，征退税率之差计入成本。',
  q_margin: '目标利润率',
  q_margin_basis: '利润率基于',
  q_basis_price: '售价',
  q_basis_cost: '成本（加成率）',
  q_overhead: '管理费用',
  q_overhead_hint: '按不含税成本加计。',
  q_floor: '最低可接受利润率',
  q_vat: '增值税率',
  q_decimals: '单价保留到',
  q_valid: '报价有效期',
  q_lead: '交货期',
  q_dest_tax: '目的国税费（DDP）',
  q_valuation: '关税计税基础',
  q_valuation_cif: 'CIF 价（欧盟、英国及多数国家）',
  q_valuation_fob: 'FOB 价（美国、加拿大、澳大利亚）',
  q_import_vat: '进口增值税 / GST',
  q_import_fees: '其他进口费用',
  q_import_fees_us: 'MPF 0.3464%（有最低额和上限）+ HMF 0.125%。',
  q_vat_recoverable: '我们可以抵扣进口增值税',
  q_notes: '报价单备注',
  q_notes_hint: '印在英文报价单上。留空则使用标准措辞。',
  q_sheet_terms: '报价单上同时列出',
  q_quoting_term: '报价术语',
  q_term: '贸易术语',
  q_total_at: '{term} 总价',
  q_shipment_sum: '{ctn} 箱 · {cbm} 立方米 · {kg} 公斤',
  q_margin_earned: '实际利润率',
  q_markup_earned: '实际加成率',
  q_profit_is: '本单利润 {v}',
  q_fx_cost: '换汇成本',
  q_fx_cost_is: '按 FOB 计，每赚 1 单位外币花费的人民币。今日汇率：{rate}（每 {cur}）。',
  q_w_part_carton: '{line}：最后一箱只有 {n} 件。',
  q_w_rebate_gt_vat: '{line}：退税率高于增值税率。',
  q_w_no_carton: '{line}：缺少纸箱尺寸，无法装柜或分摊运费。',
  q_w_ddp_no_duty: '{line}：进口关税为 0%。报 DDP 前请核实该 HS 编码的税率。',
  q_w_no_fx: '缺少汇率。请先填入每单位报价币种兑人民币的汇率，再看价格。',
  q_w_no_plan: '没有合适的运输方式。请至少填一项运价，并确认纸箱能通过柜门。',
  q_w_sea_term_air: '{term} 只适用于海运。空运请报 FCA、CPT 或 CIP。',
  q_w_fca_hint: '集装箱是在码头交接，而不是装上船时交接。《国际贸易术语解释通则® 2020》建议集装箱货物用 FCA 代替 FOB。',
  q_w_below_floor: '利润率低于你的最低可接受利润率。',
  q_w_lcl_big: '拼箱超过 15 立方米。整柜通常更便宜，也更安全。',
  q_ladder: '贸易术语阶梯',
  q_ladder_basis: '显示',
  q_ladder_order: '整单',
  q_ladder_unit: '单价：{name}',
  q_ladder_hint: '每个术语都按独立报价计算，利润率与当前报价一致。点击某个术语即可改用它报价。',
  q_add_haulage: '+ 拖车、报关',
  q_add_origin: '+ 港杂',
  q_add_freight: '+ 运费',
  q_add_insurance: '+ 保险',
  q_add_dest: '+ 目的港、派送',
  q_add_duty: '+ 关税、进口增值税',
  q_breakdown: '价格构成',
  q_breakdown_hint: '按 {term} 计的一件产品，售价 {price}。',
  q_part_goods: '货值（不含税）',
  q_part_overhead: '管理费用',
  q_part_tax: '未退增值税',
  q_part_origin: '拖车、报关、港杂',
  q_part_freight: '运费和保险',
  q_part_destination: '目的港、关税、税',
  q_part_terms: '佣金、银行、资金',
  q_part_profit: '利润',
  q_load: '装柜方案',
  q_load_empty: '填入带纸箱尺寸的产品和至少一项运价，即可看到装柜方案。',
  q_load_air: '空运按实重和体积重中较大者计费（1 立方米 = 167 公斤）。',
  q_load_lcl: '拼箱按计费吨收费：立方米与吨数取大者，最低 1。',
  q_load_view: '{type} 装载 {n} 箱',
  q_volume: '体积',
  q_weight: '重量',
  q_length: '柜内长度',
  q_ctns: '{n} 箱',
  q_wall: '每排',
  q_fill: '箱 {name} 还能装下。报 {qty} 件即可装满：单位运费下降 {drop}，订单增加 {value}。',
  q_fill_apply: '采用这个数量',
  q_modes: '所有运输方式',
  q_mode: '方式',
  q_fill_col: '末柜装载率',
  q_to_port_unit: '单位运费',
  q_cheapest: '最便宜',
  q_plan_auto: '恢复为最便宜的方式',
  q_modes_hint: '到目的港的单位成本，含拖车和起运港杂费。点击某一方式即可采用。',
  q_mode_lcl: '拼箱 {n} 计费吨',
  q_mode_air: '空运 {n} 公斤',
  q_money: '汇率与税',
  q_breakeven: '盈亏平衡汇率',
  q_breakeven_is: '人民币兑 {cur} 升值 {pct} 以内，这份报价仍不亏损。',
  q_breakeven_none: '按今日汇率，这份报价亏损。',
  q_rebate_mfr: '免抵退税额',
  q_rebate_trader: '退税额',
  q_rebate_is: '不能退回的增值税：{v}。',
  q_finance: '等待收款的资金成本',
  q_sens: '汇率或运费变了怎么办？',
  q_sens_label: '按当前报价计算的利润率',
  q_sens_corner: '运费 ↓ 汇率 →',
  q_sens_today: '今日',
  q_sens_hint: '行：运费变化。列：每单位报价币种兑人民币。红色低于最低利润率，绿色达到目标。',
  q_sens_hint_fob: '你报的是 {term}，运费风险由买家承担，所以每一行都一样。列：每单位报价币种兑人民币。',
  q_breaks: '按整柜数量报价',
  q_breaks_load: '订单',
  q_breaks_total: '总价',
  q_breaks_now: '当前报价',
  q_breaks_full: '整 {type}',
  q_breaks_hint: '所有产品按同一比例放大，直到装满一个柜。可作为阶梯价格表。',
  q_list_title: '已存报价',
  q_list_label: '{n} 份报价',
  q_list_drift_hint: '彩色利润率表示未成交报价按 {date} 参考汇率的实际利润率。',
  q_list_empty: '还没有保存的报价。',
  q_list_quote: '报价',
  q_list_status: '状态',
  q_list_total: '总价',
  q_list_margin: '利润率',
  q_list_actions: '操作',
  q_list_today: '现在 {m}',
  q_status_draft: '草稿',
  q_status_sent: '已发送',
  q_status_won: '已成交',
  q_status_lost: '未成交',
  q_duplicate: '复制',
  q_duplicated: '已复制为新报价',

  tr_kicker: '样品与售后追踪器 · {n} 项进行中',
  tr_title: '所有买家往来，一块看板',
  tr_import: '导入 CSV',
  tr_export: '导出 CSV',
  tr_new_case: '新建售后案件',
  tr_new_sample: '+ 登记样品',
  tr_kpi_win: '样品转订单',
  tr_kpi_win_n: '已定结果 {n} 个，成交 {won} 个',
  tr_kpi_days: '到下单的中位天数',
  tr_kpi_days_n: '从样品申请到采购订单',
  tr_kpi_spend: '样品支出',
  tr_kpi_spend_n: '样品和快递费，近 {n} 天',
  tr_kpi_roi: '每 ¥1 样品换来',
  tr_kpi_roi_n: '订单金额 {po}',
  tr_kpi_8d: '按时遏制',
  tr_kpi_8d_n: '{n} 个案件未结',
  tr_today: '今日待办',
  tr_today_n: '{n} 项',
  tr_today_empty: '未来 24 小时没有到期事项。',
  tr_open: '打开',
  tr_act_touch_short: '已联系',
  tr_touched: '已记录',
  tr_track: '查件',
  tr_snooze_1: '延后 1 天',
  tr_snooze_2: '延后 2 天',
  tr_snooze_7: '延后 1 周',
  tr_why_approve: '新申请：批准并向买家确认日期。',
  tr_why_update: '制作中：给买家发一个进度更新。',
  tr_why_qc: '检查品质，出货前发照片。',
  tr_why_track: '运输 {n} 天：查看物流状态。',
  tr_why_feedback: '已签收 {n} 天：询问反馈。',
  tr_why_cold: '已签收 {n} 天，买家热度在下降。',
  tr_why_step: '{step} {name} 到期。',
  tr_tab_samples: '样品 · {n}',
  tr_tab_cases: '售后 · {n}',
  tr_tab_insights: '分析',
  tr_search: '搜索买家、产品、运单号…',
  tr_all_countries: '全部国家',
  tr_board_hint: '卡片下方的条是买家热度：每天没有回复就降一点，样品签收后降得最快。拖动卡片可以移动阶段。',
  tr_empty_samples: '还没有样品',
  tr_empty_samples_body: '每收到一个样品申请就登记一条。追踪器会告诉你什么时候该跟进哪个买家。',
  tr_import_hint: '已经在用 Excel 记录？导入 CSV 即可，列名如 客户、国家、产品、数量、快递、运单号，英文列名也可以。',
  tr_empty_cases: '没有售后案件',
  tr_empty_cases_body: '买家反馈问题时，新建一个案件。每个案件按 8D 方法推进，时限与买家的要求一致。',
  tr_col_requested: '已申请',
  tr_col_making: '制作与质检',
  tr_col_transit: '运输中',
  tr_col_delivered: '等待反馈',
  tr_col_decided: '已定结果',
  tr_ccol_open: '新案件',
  tr_ccol_contained: '已遏制',
  tr_ccol_fixing: '整改中',
  tr_ccol_preventing: '预防中',
  tr_ccol_closed: '已结案',
  tr_stage: '阶段',
  tr_stage_requested: '已申请',
  tr_stage_making: '制作中',
  tr_stage_qc: '质检',
  tr_stage_transit: '运输中',
  tr_stage_delivered: '已签收',
  tr_stage_won: '已成交',
  tr_stage_lost: '未成交',
  tr_no_buyer: '未命名买家',
  tr_card_won: '订单 ${v}',
  tr_card_lost: '未成交 · {r}',
  tr_policy_free: '免费',
  tr_policy_buyer_pays: '买家付费',
  tr_policy_credit: '首单抵扣',
  tr_import_big: '文件超过 2 MB，请拆分后分批导入。',
  tr_import_none: '没有找到数据行。第一行必须是列名。',
  tr_imported: '已导入 {n} 个样品',
  tr_deleted: '已删除',
  tr_sample_label: '样品',
  tr_case_label: '售后案件',
  tr_next_contact: '下次联系',
  tr_warmth: '热度',
  tr_next_action: '下一步',
  tr_act_approve: '批准并开始制作',
  tr_act_qc: '已做好：进入质检',
  tr_act_dispatch: '寄出',
  tr_act_delivered: '标记为已签收',
  tr_act_won: '成交：记录订单',
  tr_act_lost: '标记未成交',
  tr_act_reopen: '重新打开',
  tr_act_touch: '记录联系',
  tr_courier: '快递公司',
  tr_courier_other: '其他',
  tr_awb: '运单号',
  tr_po_value: '订单金额',
  tr_lost_reason: '未成交原因',
  tr_lost_price: '价格',
  tr_lost_quality: '质量',
  tr_lost_lead_time: '交期',
  tr_lost_no_reply: '买家不再回复',
  tr_lost_cancelled: '项目取消',
  tr_lost_competitor: '选了竞争对手',
  tr_lost_other: '其他',
  tr_won_po: '已成交 · 订单 ${v}',
  tr_lost_because: '未成交 · {r}',
  tr_contact_note: '沟通内容',
  tr_contact_note_ph: '例如 下周测试完成',
  tr_details: '详情',
  tr_buyer: '买家',
  tr_country: '国家',
  tr_contact: '联系人',
  tr_email: '邮箱',
  tr_item: '产品',
  tr_qty: '数量',
  tr_cost_policy: '费用承担',
  tr_goods_cost: '样品成本',
  tr_courier_cost: '快递费',
  tr_notes: '备注',
  tr_track_with: '在 {c} 查件',
  tr_links: '关联',
  tr_open_quote: '打开报价',
  tr_make_quote: '生成报价',
  tr_open_case: '新建售后案件',
  tr_from_sample: '来自样品 {ref}',
  tr_activity: '动态',
  tr_log_created: '已创建',
  tr_log_stage: '进入「{stage}」',
  tr_log_touch: '已联系',
  tr_log_snooze: '延后 {n} 天',
  tr_log_step: '{step} 完成',
  tr_delete_sample: '删除这个样品',
  tr_delete_case: '删除这个案件',
  tr_compose: '给买家写信',
  tr_compose_lang: '英文',
  tr_compose_template: '邮件类型',
  tr_compose_tone: '语气',
  tr_tone_formal: '正式',
  tr_tone_friendly: '亲切',
  tr_subject: 'Subject',
  tr_copy: '复制',
  tr_copied: '已复制',
  tr_copy_failed: '无法复制，请手动选中文字复制。',
  tr_open_email: '用邮件打开',
  tr_compose_hint: '只根据本条记录生成，不会发送到任何地方。发送前请通读；[方括号] 里的内容需要你补充。',
  tr_tpl_dispatched: '样品已寄出',
  tr_tpl_delivered: '样品已到达',
  tr_tpl_feedback: '询问反馈',
  tr_tpl_cold: '唤醒沉默的买家',
  tr_tpl_won: '感谢下单',
  tr_tpl_acknowledge: '已收到投诉',
  tr_tpl_containment: '遏制措施已到位',
  tr_tpl_rootcause: '根本原因与整改',
  tr_tpl_close: '案件关闭',
  tr_opened: '开案于 {date}',
  tr_8d: '8D 进度',
  tr_8d_hint: '时限从开案时间起算',
  tr_d_D0: '准备',
  tr_d_D1: '成立小组',
  tr_d_D2: '描述问题',
  tr_d_D3: '临时遏制',
  tr_d_D4: '根本原因',
  tr_d_D5: '选定对策',
  tr_d_D6: '实施验证',
  tr_d_D7: '预防再发',
  tr_d_D8: '结案',
  tr_d_D0_help: '收集事实：照片、批号、数量。判断是否需要紧急响应。',
  tr_d_D1_help: '确定负责解决的人：品质、生产，以及和买家沟通的人。',
  tr_d_D2_help: '用数字描述问题：什么、哪里、何时、多少（5W2H）。',
  tr_d_D3_help: '先保护买家：挑选或隔离库存、补发货物、暂停出货。买家通常要求 24 小时内完成。',
  tr_d_D4_help: '找出问题为何发生、为何没被发现，并用数据证明。',
  tr_d_D5_help: '为每个根本原因选定永久对策。',
  tr_d_D6_help: '落实对策，并证明有效。',
  tr_d_D7_help: '修改流程、图纸或检验，让其他产品也不会再发生。',
  tr_d_D8_help: '与买家确认，感谢团队，关闭案件。',
  tr_step_done: '完成',
  tr_done_at: '{date} 完成',
  tr_step_note: '做了什么',
  tr_step_reopen: '重新打开此步骤',
  tr_step_complete: '标记 {step} 完成',
  tr_sev_critical: '严重',
  tr_sev_major: '主要',
  tr_sev_minor: '轻微',
  tr_type_quality: '质量缺陷',
  tr_type_shortage: '少发或错发',
  tr_type_damage: '运输损坏',
  tr_type_docs: '单证问题',
  tr_type_late: '延迟交货',
  tr_type_other: '其他',
  tr_case_title: '问题',
  tr_case_title_ph: '例如 DN65 阀门阀座泄漏',
  tr_severity: '严重程度',
  tr_type: '类型',
  tr_product: '产品',
  tr_po_ref: '订单号',
  tr_lot: '批号',
  tr_claim: '索赔金额',
  tr_affected: '不良数量',
  tr_total_qty: '出货数量',
  tr_root_cause: '根本原因',
  tr_resolution: '处理方式',
  tr_case_cost: '我方损失',
  tr_case_cost_hint: '补发货物、运费、折让、人工。计入质量成本图表。',
  tr_cause_material: '材料',
  tr_cause_process: '工艺',
  tr_cause_design: '设计',
  tr_cause_packaging: '包装',
  tr_cause_transport: '运输',
  tr_cause_supplier: '供应商',
  tr_cause_human: '人为失误',
  tr_cause_unknown: '尚未查明',
  tr_res_replacement: '补发',
  tr_res_credit: '折让单',
  tr_res_refund: '退款',
  tr_res_repair: '维修',
  tr_res_rework: '返工',
  tr_res_rejected: '拒绝索赔',
  tr_insights_empty: '还没有可分析的数据',
  tr_insights_empty_body: '登记样品或售后案件后，这里会出现分析。',
  tr_period: '时间段',
  tr_period_days: '近 {n} 天',
  tr_fx_setting: '每美元兑人民币（用于回报计算）',
  tr_funnel: '从申请到订单',
  tr_funnel_requested: '已申请',
  tr_funnel_transit: '已寄出',
  tr_funnel_delivered: '已签收',
  tr_funnel_won: '拿到订单',
  tr_funnel_hint: '已定结果的样品中 {rate} 转成了订单（{n} 个中的 {won} 个）。',
  tr_funnel_none: '还没有定结果的样品。',
  tr_dwell: '样品卡在哪里',
  tr_dwell_hint: '每个阶段停留的中位天数。最长的一项（锈红色）最值得先看。',
  tr_by_country: '按国家',
  tr_samples_n: '样品',
  tr_win: '成交率',
  tr_spend: '支出',
  tr_po_sum: '订单',
  tr_lost_why: '为什么没成交',
  tr_lost_none: '这个时间段没有未成交的样品。',
  tr_pareto: '按根本原因的质量成本',
  tr_pareto_none: '这个时间段没有记录售后成本。',
  tr_pareto_hint: '锈红色的柱子占了前 80% 的成本，先解决这些原因回报最大。',
  tr_quality_share: '占订单金额 {pct}',
}

const TW = {
  nav_quoting: '報價',
  nav_tracker: '樣品售後',
  home_quoting_cta: '開啟報價台',
  home_tracker_cta: '開啟追蹤器',

  tl_cancel: '取消',
  tl_days: '{n} 天',
  tl_days_short: '{n}天',
  tl_hours: '{n} 小時',
  tl_in: '{span}後',
  tl_late: '已逾期 {span}',
  tl_delete: '刪除',
  tl_delete_confirm: '確認刪除',
  tl_saved_device: '已儲存在本裝置',
  tl_saved_guest: '僅儲存在此瀏覽器。',
  tl_synced: '已同步到你的帳戶',
  tl_syncing: '同步中…',
  tl_sync_error: '同步失敗，內容已儲存在本裝置。',

  q_kicker: '出口報價引擎',
  q_title: '報價台',
  q_valid_to: '有效期至 {date}',
  q_expired: '已過期',
  q_no_buyer: '尚未填寫買家',
  q_quotes: '已存報價（{n}）',
  q_new: '新增報價',
  q_revise: '新版本',
  q_revised: '已建立新版本',
  q_print: '列印報價單',
  q_example_note: '以下為範例數據。送出任何報價前，請換成你自己的成本和貨代運價。',
  q_start: '從左側填寫第一個產品，或載入一個完整範例，看看每個面板的效果。',
  q_load_example: '載入範例',
  q_to_tracker: '為該買家登記樣品申請',
  q_to_tracker_hint: '開啟樣品與售後追蹤器，並自動填好買家和產品。',
  q_inputs: '報價輸入',
  q_s_parties: '買家',
  q_s_lines: '產品',
  q_s_route: '路線與運費',
  q_s_money: '匯率與付款',
  q_s_margin: '利潤與稅',
  q_buyer: '買家公司',
  q_buyer_ph: '報價單上顯示的公司名稱',
  q_contact: '聯絡人',
  q_city: '城市',
  q_you: '報價單上的我方資訊',
  q_you_company: '我方公司',
  q_you_address: '地址',
  q_you_name: '你的姓名',
  q_you_email: '電子郵件',
  q_you_phone: '電話',
  q_you_hint: '儲存在本裝置，用於每份報價單和郵件。',
  q_lines_n: '{n} 個產品',
  q_line_name: '產品',
  q_line_name_ph: '產品名稱，例如 黃銅球閥 DN25',
  q_unit_cost: '單位成本',
  q_qty: '數量',
  q_price_override: '你的報價',
  q_price_auto: '計算結果：{p}。輸入價格可覆蓋。',
  q_auto: '自動',
  q_cost_incl_vat: '單位成本為含稅價',
  q_line_more: '包裝、HS 編碼和稅率',
  q_line_less: '收起',
  q_spec: '規格',
  q_spec_ph: '材質、壓力等級、表面處理',
  q_hs: 'HS 編碼',
  q_packing: '外銷紙箱',
  q_per_carton: '每箱件數',
  q_carton_kg: '每箱毛重',
  q_upright: '此面朝上',
  q_rebate: '出口退稅率',
  q_rebate_hint: '該 HS 編碼的退稅率（0–13%）。稅率會調整，報價前請核實。',
  q_duty: '目的國進口關稅',
  q_duty_hint: '僅用於 DDP。請把額外關稅（如美國 301 關稅）一併計入。',
  q_line_dup: '複製',
  q_line_remove: '刪除',
  q_line_add: '+ 新增產品',
  q_paste: '從 Excel 貼上',
  q_paste_hint: '每行一個產品：品名、數量、單位成本 ¥、每箱件數、箱長、寬、高（公分）、每箱毛重、HS 編碼。',
  q_paste_add: '新增這些行',
  q_paste_none: '沒有找到帶品名的行。',
  q_paste_done: '已新增 {n} 個產品',
  q_origin: '裝貨港',
  q_origin_place: '工廠所在地',
  q_origin_place_ph: '城市、省份（用於 EXW）',
  q_dest_country: '目的國',
  q_dest_other: '其他國家',
  q_dest_port: '卸貨港',
  q_dest_place: '買家收貨地',
  q_dest_place_ph: '城市（用於 DAP 和 DDP）',
  q_rates: '你的貨代運價',
  q_rate_freight: '海運 / 空運費（$）',
  q_rate_origin: '起運港雜費（¥）',
  q_rate_haulage: '拖車到港（¥）',
  q_rate_dest: '目的港雜費（$）',
  q_rate_delivery: '派送到門（$）',
  q_rate_unit: '計費單位',
  q_per_wm: '計費噸',
  q_per_box: '櫃',
  q_per_kg: '公斤',
  q_air: '空運',
  q_rates_hint: '沒有的運輸方式留空即可。整櫃的拖車和派送按櫃計，併櫃和空運按票計。Nexallure 從不猜測運費。',
  q_export_docs: '出口報關和單證費',
  q_import_broker: '目的國報關代理費',
  q_payload: '每櫃限重',
  q_currency: '報價幣別',
  q_fx: '每 {cur} 兌人民幣',
  q_fx_fetch: '取得參考匯率',
  q_fx_loading: '取得中…',
  q_fx_done: '已載入 {date} 的參考匯率',
  q_fx_failed: '無法連線匯率服務，請填入銀行匯率。',
  q_fx_hint: '請用銀行實際給你的結匯匯率。',
  q_fx_asof: '歐洲央行 {date} 參考匯率。銀行結匯價通常略低。',
  q_payment: '付款條件',
  q_pay_TT_ADVANCE: 'T/T 100% 預付',
  q_pay_TT_30_70_BL: 'T/T 30% 訂金，70% 見提單副本付款',
  q_pay_TT_30_70_BEFORE: 'T/T 30% 訂金，70% 出貨前付清',
  q_pay_LC_SIGHT: '即期信用狀',
  q_pay_LC_60: '60 天遠期信用狀',
  q_pay_DP_SIGHT: '即期付款交單 D/P',
  q_pay_OA_30: '記帳 30 天',
  q_pay_OA_60: '記帳 60 天',
  q_tranche: '{pct}% 貨款：出貨後第幾天到帳',
  q_tranche_hint: '負數表示出貨前到帳。',
  q_days_short: '天',
  q_capital: '資金成本',
  q_bank_pct: '銀行手續費',
  q_bank_flat: '銀行固定費用',
  q_sinosure: '中國信保費率',
  q_commission: '中間商佣金',
  q_insurance: '貨物保險費率',
  q_insurance_hint: '按 CIF 價的 {m}% 投保，符合國貿條規的要求。',
  q_entity: '出口主體',
  q_entity_mfr: '生產企業 · 免抵退',
  q_entity_trader: '外貿企業 · 免退',
  q_entity_mfr_hint: '徵稅率與退稅率之差按 FOB 價計入成本。',
  q_entity_trader_hint: '按含稅採購成本退稅，徵退稅率之差計入成本。',
  q_margin: '目標利潤率',
  q_margin_basis: '利潤率基於',
  q_basis_price: '售價',
  q_basis_cost: '成本（加成率）',
  q_overhead: '管理費用',
  q_overhead_hint: '按未稅成本加計。',
  q_floor: '最低可接受利潤率',
  q_vat: '增值稅率',
  q_decimals: '單價保留到',
  q_valid: '報價有效期',
  q_lead: '交期',
  q_dest_tax: '目的國稅費（DDP）',
  q_valuation: '關稅計稅基礎',
  q_valuation_cif: 'CIF 價（歐盟、英國及多數國家）',
  q_valuation_fob: 'FOB 價（美國、加拿大、澳洲）',
  q_import_vat: '進口增值稅 / GST',
  q_import_fees: '其他進口費用',
  q_import_fees_us: 'MPF 0.3464%（有最低額和上限）+ HMF 0.125%。',
  q_vat_recoverable: '我們可以扣抵進口增值稅',
  q_notes: '報價單備註',
  q_notes_hint: '印在英文報價單上。留空則使用標準措辭。',
  q_sheet_terms: '報價單上同時列出',
  q_quoting_term: '報價條件',
  q_term: '國貿條規',
  q_total_at: '{term} 總價',
  q_shipment_sum: '{ctn} 箱 · {cbm} 立方公尺 · {kg} 公斤',
  q_margin_earned: '實際利潤率',
  q_markup_earned: '實際加成率',
  q_profit_is: '本單利潤 {v}',
  q_fx_cost: '換匯成本',
  q_fx_cost_is: '按 FOB 計，每賺 1 單位外幣花費的人民幣。今日匯率：{rate}（每 {cur}）。',
  q_w_part_carton: '{line}：最後一箱只有 {n} 件。',
  q_w_rebate_gt_vat: '{line}：退稅率高於增值稅率。',
  q_w_no_carton: '{line}：缺少紙箱尺寸，無法裝櫃或分攤運費。',
  q_w_ddp_no_duty: '{line}：進口關稅為 0%。報 DDP 前請核實該 HS 編碼的稅率。',
  q_w_no_fx: '缺少匯率。請先填入每單位報價幣別兌人民幣的匯率，再看價格。',
  q_w_no_plan: '沒有合適的運輸方式。請至少填一項運價，並確認紙箱能通過櫃門。',
  q_w_sea_term_air: '{term} 只適用於海運。空運請報 FCA、CPT 或 CIP。',
  q_w_fca_hint: '貨櫃是在碼頭交接，而不是裝上船時交接。國貿條規® 2020 建議貨櫃貨物用 FCA 取代 FOB。',
  q_w_below_floor: '利潤率低於你的最低可接受利潤率。',
  q_w_lcl_big: '併櫃超過 15 立方公尺。整櫃通常更便宜，也更安全。',
  q_ladder: '國貿條規階梯',
  q_ladder_basis: '顯示',
  q_ladder_order: '整單',
  q_ladder_unit: '單價：{name}',
  q_ladder_hint: '每個條規都按獨立報價計算，利潤率與目前報價一致。點選某個條規即可改用它報價。',
  q_add_haulage: '+ 拖車、報關',
  q_add_origin: '+ 港雜',
  q_add_freight: '+ 運費',
  q_add_insurance: '+ 保險',
  q_add_dest: '+ 目的港、派送',
  q_add_duty: '+ 關稅、進口增值稅',
  q_breakdown: '價格構成',
  q_breakdown_hint: '按 {term} 計的一件產品，售價 {price}。',
  q_part_goods: '貨值（未稅）',
  q_part_overhead: '管理費用',
  q_part_tax: '未退增值稅',
  q_part_origin: '拖車、報關、港雜',
  q_part_freight: '運費和保險',
  q_part_destination: '目的港、關稅、稅',
  q_part_terms: '佣金、銀行、資金',
  q_part_profit: '利潤',
  q_load: '裝櫃方案',
  q_load_empty: '填入帶紙箱尺寸的產品和至少一項運價，即可看到裝櫃方案。',
  q_load_air: '空運按實重和材積重中較大者計費（1 立方公尺 = 167 公斤）。',
  q_load_lcl: '併櫃按計費噸收費：立方公尺與噸數取大者，最低 1。',
  q_load_view: '{type} 裝載 {n} 箱',
  q_volume: '體積',
  q_weight: '重量',
  q_length: '櫃內長度',
  q_ctns: '{n} 箱',
  q_wall: '每排',
  q_fill: '箱 {name} 還裝得下。報 {qty} 件即可裝滿：單位運費下降 {drop}，訂單增加 {value}。',
  q_fill_apply: '採用這個數量',
  q_modes: '所有運輸方式',
  q_mode: '方式',
  q_fill_col: '末櫃裝載率',
  q_to_port_unit: '單位運費',
  q_cheapest: '最便宜',
  q_plan_auto: '恢復為最便宜的方式',
  q_modes_hint: '到目的港的單位成本，含拖車和起運港雜費。點選某一方式即可採用。',
  q_mode_lcl: '併櫃 {n} 計費噸',
  q_mode_air: '空運 {n} 公斤',
  q_money: '匯率與稅',
  q_breakeven: '損益平衡匯率',
  q_breakeven_is: '人民幣兌 {cur} 升值 {pct} 以內，這份報價仍不虧損。',
  q_breakeven_none: '按今日匯率，這份報價虧損。',
  q_rebate_mfr: '免抵退稅額',
  q_rebate_trader: '退稅額',
  q_rebate_is: '無法退回的增值稅：{v}。',
  q_finance: '等待收款的資金成本',
  q_sens: '匯率或運費變了怎麼辦？',
  q_sens_label: '按目前報價計算的利潤率',
  q_sens_corner: '運費 ↓ 匯率 →',
  q_sens_today: '今日',
  q_sens_hint: '列：運費變化。欄：每單位報價幣別兌人民幣。紅色低於最低利潤率，綠色達到目標。',
  q_sens_hint_fob: '你報的是 {term}，運費風險由買家承擔，所以每一列都一樣。欄：每單位報價幣別兌人民幣。',
  q_breaks: '按整櫃數量報價',
  q_breaks_load: '訂單',
  q_breaks_total: '總價',
  q_breaks_now: '目前報價',
  q_breaks_full: '整 {type}',
  q_breaks_hint: '所有產品按同一比例放大，直到裝滿一個櫃。可作為階梯價格表。',
  q_list_title: '已存報價',
  q_list_label: '{n} 份報價',
  q_list_drift_hint: '彩色利潤率表示未成交報價按 {date} 參考匯率的實際利潤率。',
  q_list_empty: '還沒有儲存的報價。',
  q_list_quote: '報價',
  q_list_status: '狀態',
  q_list_total: '總價',
  q_list_margin: '利潤率',
  q_list_actions: '操作',
  q_list_today: '現在 {m}',
  q_status_draft: '草稿',
  q_status_sent: '已送出',
  q_status_won: '已成交',
  q_status_lost: '未成交',
  q_duplicate: '複製',
  q_duplicated: '已複製為新報價',

  tr_kicker: '樣品與售後追蹤器 · {n} 項進行中',
  tr_title: '所有買家往來，一塊看板',
  tr_import: '匯入 CSV',
  tr_export: '匯出 CSV',
  tr_new_case: '新增售後案件',
  tr_new_sample: '+ 登記樣品',
  tr_kpi_win: '樣品轉訂單',
  tr_kpi_win_n: '已定結果 {n} 個，成交 {won} 個',
  tr_kpi_days: '到下單的中位天數',
  tr_kpi_days_n: '從樣品申請到採購訂單',
  tr_kpi_spend: '樣品支出',
  tr_kpi_spend_n: '樣品和快遞費，近 {n} 天',
  tr_kpi_roi: '每 ¥1 樣品換來',
  tr_kpi_roi_n: '訂單金額 {po}',
  tr_kpi_8d: '準時圍堵',
  tr_kpi_8d_n: '{n} 個案件未結',
  tr_today: '今日待辦',
  tr_today_n: '{n} 項',
  tr_today_empty: '未來 24 小時沒有到期事項。',
  tr_open: '開啟',
  tr_act_touch_short: '已聯絡',
  tr_touched: '已記錄',
  tr_track: '查件',
  tr_snooze_1: '延後 1 天',
  tr_snooze_2: '延後 2 天',
  tr_snooze_7: '延後 1 週',
  tr_why_approve: '新申請：核准並向買家確認日期。',
  tr_why_update: '製作中：給買家發一個進度更新。',
  tr_why_qc: '檢查品質，出貨前寄照片。',
  tr_why_track: '運送 {n} 天：查看物流狀態。',
  tr_why_feedback: '已簽收 {n} 天：詢問回饋。',
  tr_why_cold: '已簽收 {n} 天，買家熱度在下降。',
  tr_why_step: '{step} {name} 到期。',
  tr_tab_samples: '樣品 · {n}',
  tr_tab_cases: '售後 · {n}',
  tr_tab_insights: '分析',
  tr_search: '搜尋買家、產品、運單號…',
  tr_all_countries: '全部國家',
  tr_board_hint: '卡片下方的條是買家熱度：每天沒有回覆就降一點，樣品簽收後降得最快。拖曳卡片可以移動階段。',
  tr_empty_samples: '還沒有樣品',
  tr_empty_samples_body: '每收到一個樣品申請就登記一筆。追蹤器會告訴你什麼時候該跟進哪個買家。',
  tr_import_hint: '已經在用 Excel 記錄？匯入 CSV 即可，欄名如 客戶、國家、產品、數量、快遞、運單號，英文欄名也可以。',
  tr_empty_cases: '沒有售後案件',
  tr_empty_cases_body: '買家回報問題時，新增一個案件。每個案件按 8D 方法推進，時限與買家的要求一致。',
  tr_col_requested: '已申請',
  tr_col_making: '製作與品檢',
  tr_col_transit: '運送中',
  tr_col_delivered: '等待回饋',
  tr_col_decided: '已定結果',
  tr_ccol_open: '新案件',
  tr_ccol_contained: '已圍堵',
  tr_ccol_fixing: '改善中',
  tr_ccol_preventing: '預防中',
  tr_ccol_closed: '已結案',
  tr_stage: '階段',
  tr_stage_requested: '已申請',
  tr_stage_making: '製作中',
  tr_stage_qc: '品檢',
  tr_stage_transit: '運送中',
  tr_stage_delivered: '已簽收',
  tr_stage_won: '已成交',
  tr_stage_lost: '未成交',
  tr_no_buyer: '未命名買家',
  tr_card_won: '訂單 ${v}',
  tr_card_lost: '未成交 · {r}',
  tr_policy_free: '免費',
  tr_policy_buyer_pays: '買家付費',
  tr_policy_credit: '首單扣抵',
  tr_import_big: '檔案超過 2 MB，請拆分後分批匯入。',
  tr_import_none: '沒有找到資料列。第一列必須是欄名。',
  tr_imported: '已匯入 {n} 個樣品',
  tr_deleted: '已刪除',
  tr_sample_label: '樣品',
  tr_case_label: '售後案件',
  tr_next_contact: '下次聯絡',
  tr_warmth: '熱度',
  tr_next_action: '下一步',
  tr_act_approve: '核准並開始製作',
  tr_act_qc: '已做好：進入品檢',
  tr_act_dispatch: '寄出',
  tr_act_delivered: '標記為已簽收',
  tr_act_won: '成交：記錄訂單',
  tr_act_lost: '標記未成交',
  tr_act_reopen: '重新開啟',
  tr_act_touch: '記錄聯絡',
  tr_courier: '快遞公司',
  tr_courier_other: '其他',
  tr_awb: '運單號',
  tr_po_value: '訂單金額',
  tr_lost_reason: '未成交原因',
  tr_lost_price: '價格',
  tr_lost_quality: '品質',
  tr_lost_lead_time: '交期',
  tr_lost_no_reply: '買家不再回覆',
  tr_lost_cancelled: '專案取消',
  tr_lost_competitor: '選了競爭對手',
  tr_lost_other: '其他',
  tr_won_po: '已成交 · 訂單 ${v}',
  tr_lost_because: '未成交 · {r}',
  tr_contact_note: '溝通內容',
  tr_contact_note_ph: '例如 下週測試完成',
  tr_details: '詳情',
  tr_buyer: '買家',
  tr_country: '國家',
  tr_contact: '聯絡人',
  tr_email: '電子郵件',
  tr_item: '產品',
  tr_qty: '數量',
  tr_cost_policy: '費用負擔',
  tr_goods_cost: '樣品成本',
  tr_courier_cost: '快遞費',
  tr_notes: '備註',
  tr_track_with: '在 {c} 查件',
  tr_links: '關聯',
  tr_open_quote: '開啟報價',
  tr_make_quote: '產生報價',
  tr_open_case: '新增售後案件',
  tr_from_sample: '來自樣品 {ref}',
  tr_activity: '動態',
  tr_log_created: '已建立',
  tr_log_stage: '進入「{stage}」',
  tr_log_touch: '已聯絡',
  tr_log_snooze: '延後 {n} 天',
  tr_log_step: '{step} 完成',
  tr_delete_sample: '刪除這個樣品',
  tr_delete_case: '刪除這個案件',
  tr_compose: '給買家寫信',
  tr_compose_lang: '英文',
  tr_compose_template: '郵件類型',
  tr_compose_tone: '語氣',
  tr_tone_formal: '正式',
  tr_tone_friendly: '親切',
  tr_subject: 'Subject',
  tr_copy: '複製',
  tr_copied: '已複製',
  tr_copy_failed: '無法複製，請手動選取文字複製。',
  tr_open_email: '用郵件開啟',
  tr_compose_hint: '只根據本筆紀錄產生，不會傳送到任何地方。寄出前請通讀；[方括號] 裡的內容需要你補充。',
  tr_tpl_dispatched: '樣品已寄出',
  tr_tpl_delivered: '樣品已到達',
  tr_tpl_feedback: '詢問回饋',
  tr_tpl_cold: '喚醒沉默的買家',
  tr_tpl_won: '感謝下單',
  tr_tpl_acknowledge: '已收到客訴',
  tr_tpl_containment: '圍堵措施已到位',
  tr_tpl_rootcause: '根本原因與改善',
  tr_tpl_close: '案件結案',
  tr_opened: '開案於 {date}',
  tr_8d: '8D 進度',
  tr_8d_hint: '時限從開案時間起算',
  tr_d_D0: '準備',
  tr_d_D1: '成立小組',
  tr_d_D2: '描述問題',
  tr_d_D3: '暫時圍堵',
  tr_d_D4: '根本原因',
  tr_d_D5: '選定對策',
  tr_d_D6: '執行驗證',
  tr_d_D7: '預防再發',
  tr_d_D8: '結案',
  tr_d_D0_help: '收集事實：照片、批號、數量。判斷是否需要緊急應變。',
  tr_d_D1_help: '確定負責解決的人：品保、生產，以及和買家溝通的人。',
  tr_d_D2_help: '用數字描述問題：什麼、哪裡、何時、多少（5W2H）。',
  tr_d_D3_help: '先保護買家：挑選或隔離庫存、補寄貨物、暫停出貨。買家通常要求 24 小時內完成。',
  tr_d_D4_help: '找出問題為何發生、為何沒被發現，並用數據證明。',
  tr_d_D5_help: '為每個根本原因選定永久對策。',
  tr_d_D6_help: '落實對策，並證明有效。',
  tr_d_D7_help: '修改流程、圖面或檢驗，讓其他產品也不會再發生。',
  tr_d_D8_help: '與買家確認，感謝團隊，關閉案件。',
  tr_step_done: '完成',
  tr_done_at: '{date} 完成',
  tr_step_note: '做了什麼',
  tr_step_reopen: '重新開啟此步驟',
  tr_step_complete: '標記 {step} 完成',
  tr_sev_critical: '嚴重',
  tr_sev_major: '主要',
  tr_sev_minor: '輕微',
  tr_type_quality: '品質缺陷',
  tr_type_shortage: '短少或錯寄',
  tr_type_damage: '運送損壞',
  tr_type_docs: '單證問題',
  tr_type_late: '延遲交貨',
  tr_type_other: '其他',
  tr_case_title: '問題',
  tr_case_title_ph: '例如 DN65 閥門閥座洩漏',
  tr_severity: '嚴重程度',
  tr_type: '類型',
  tr_product: '產品',
  tr_po_ref: '訂單號',
  tr_lot: '批號',
  tr_claim: '索賠金額',
  tr_affected: '不良數量',
  tr_total_qty: '出貨數量',
  tr_root_cause: '根本原因',
  tr_resolution: '處理方式',
  tr_case_cost: '我方損失',
  tr_case_cost_hint: '補寄貨物、運費、折讓、人工。計入品質成本圖表。',
  tr_cause_material: '材料',
  tr_cause_process: '製程',
  tr_cause_design: '設計',
  tr_cause_packaging: '包裝',
  tr_cause_transport: '運輸',
  tr_cause_supplier: '供應商',
  tr_cause_human: '人為失誤',
  tr_cause_unknown: '尚未查明',
  tr_res_replacement: '補寄',
  tr_res_credit: '折讓單',
  tr_res_refund: '退款',
  tr_res_repair: '維修',
  tr_res_rework: '重工',
  tr_res_rejected: '拒絕索賠',
  tr_insights_empty: '還沒有可分析的資料',
  tr_insights_empty_body: '登記樣品或售後案件後，這裡會出現分析。',
  tr_period: '期間',
  tr_period_days: '近 {n} 天',
  tr_fx_setting: '每美元兌人民幣（用於回報計算）',
  tr_funnel: '從申請到訂單',
  tr_funnel_requested: '已申請',
  tr_funnel_transit: '已寄出',
  tr_funnel_delivered: '已簽收',
  tr_funnel_won: '拿到訂單',
  tr_funnel_hint: '已定結果的樣品中 {rate} 轉成了訂單（{n} 個中的 {won} 個）。',
  tr_funnel_none: '還沒有定結果的樣品。',
  tr_dwell: '樣品卡在哪裡',
  tr_dwell_hint: '每個階段停留的中位天數。最長的一項（鏽紅色）最值得先看。',
  tr_by_country: '按國家',
  tr_samples_n: '樣品',
  tr_win: '成交率',
  tr_spend: '支出',
  tr_po_sum: '訂單',
  tr_lost_why: '為什麼沒成交',
  tr_lost_none: '這段期間沒有未成交的樣品。',
  tr_pareto: '按根本原因的品質成本',
  tr_pareto_none: '這段期間沒有記錄售後成本。',
  tr_pareto_hint: '鏽紅色的長條占了前 80% 的成本，先解決這些原因回報最大。',
  tr_quality_share: '占訂單金額 {pct}',
}

export const toolStrings = { EN, ZH, TW }
